# Generated by Django 4.0.6 on 2022-07-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='User id')),
                ('name', models.TextField(verbose_name='Nickname of user')),
            ],
            options={
                'verbose_name': 'Telegram',
            },
        ),
    ]
