# Generated by Django 4.0.6 on 2022-08-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('login', models.CharField(max_length=20, verbose_name='Login')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
            ],
        ),
    ]
